name: Lint
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: v12.20.2
      - run: npm install -ci
      - run: npm run lint
